apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: development
  labels:
    app.kubernetes.io/name: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - name: http
            containerPort: 80
